name: JOSS Paper Compilation
on:
  push:
    branches: [master]
    paths: ['paper/**']
  pull_request:
    branches: [master]
    paths: ['paper/**']

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build PDF with Docker
        run: |
          docker run --rm \
            --volume $PWD/paper:/data \
            --user $(id -u):$(id -g) \
            --env JOURNAL=joss \
            openjournals/inara

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
